const company_pro_options=[
  {
    value:'互联网/IT电子/通信',
    label:'互联网/IT电子/通信',
    children:[
      {
        value:'电子商务',
        label:'电子商务'
      },
      {
        value:'游戏',
        label:'游戏'
      },
      {
        value:'媒体',
        label:'媒体'
      },
      {
        value:'广告营销',
        label:'广告营销'
      },
      {
        value:'数据服务',
        label:'数据服务'
      },
      {
        value:'医疗健康',
        label:'医疗健康'
      },
      {
        value:'生活服务',
        label:'生活服务'
      },
      {
        value:'O2O',
        label:'O2O'
      },
      {
        value:'旅游',
        label:'旅游'
      },
      {
        value:'分类信息',
        label:'分类信息'
      },
      {
        value:'音乐/视频/阅读',
        label:'音乐/视频/阅读'
      },
      {
        value:'在线教育',
        label:'在线教育'
      },
      {
        value:'社交网络',
        label:'社交网络'
      },
      {
        value:'人力资源服务',
        label:'人力资源服务'
      },
      {
        value:'企业服务',
        label:'企业服务'
      },
      {
        value:'信息安全',
        label:'信息安全'
      },
      {
        value:'新零售',
        label:'新零售'
      },
      {
        value:'智能硬件',
        label:'智能硬件'
      },
      {
        value:'移动互联网',
        label:'移动互联网'
      },
      {
        value:'互联网',
        label:'互联网'
      },
      {
        value:'计算机软件',
        label:'计算机软件'
      },
      {
        value:'计算机硬件',
        label:'计算机硬件'
      },
      {
        value:'计算机服务',
        label:'计算机服务'
      },
      {
        value:'通信/网络设备',
        label:'通信/网络设备'
      },
      {
        value:'运营商/增值服务',
        label:'运营商/增值服务'
      },
      {
        value:'电子/半导体/集成电路',
        label:'电子/半导体/集成电路'
      }
    ]
  },
  {
    value:'广告/传媒/文化/体育',
    label:'广告/传媒/文化/体育',
    children:[
      {
        value:'广告/公关/会展',
        label:'广告/公关/会展'
      },
      {
        value:'新闻/出版',
        label:'新闻/出版'
      },
      {
        value:'广播/影视',
        label:'广播/影视'
      },
      {
        value:'文化/体育/娱乐',
        label:'文化/体育/娱乐'
      }
    ]
  },
  {
    value:'金融',
    label:'金融',
    children:[
      {
        value:'银行',
        label:'银行'
      },
      {
        value:'保险',
        label:'保险'
      },
      {
        value:'证券',
        label:'证券'
      },
      {
        value:'期货',
        label:'期货'
      },
      {
        value:'基金',
        label:'基金'
      },
      {
        value:'信托',
        label:'信托'
      },
      {
        value:'互联网金融',
        label:'互联网金融'
      },
      {
        value:'投资/融资',
        label:'投资/融资'
      },
      {
        value:'租赁/拍卖/典当/担保',
        label:'租赁/拍卖/典当/担保'
      }
    ]
  },
  {
    value:'教育培训',
    label:'教育培训',
    children:[
      {
        value:'学前教育',
        label:'学前教育'
      },
      {
        value:'院校',
        label:'院校'
      },
      {
        value:'培训机构',
        label:'培训机构'
      },
      {
        value:'学术/科研',
        label:'学术/科研'
      }
    ]
  },
  {
    value:'制药/医疗',
    label:'制药/医疗',
    children:[
      {
        value:'制药',
        label:'制药'
      },
      {
        value:'医疗/护理/卫生',
        label:'医疗/护理/卫生'
      },
      {
        value:'医疗设备/器械',
        label:'医疗设备/器械'
      }
    ]
  },
  {
    value:'交通/物流/贸易/零售',
    label:'交通/物流/贸易/零售',
    children:[
      {
        value:'交通/运输',
        label:'交通/运输'
      },
      {
        value:'物流/仓储',
        label:'物流/仓储'
      },
      {
        value:'批发/零售',
        label:'批发/零售'
      },
      {
        value:'贸易/进出口',
        label:'贸易/进出口'
      }
    ]
  },
  {
    value:'专业服务',
    label:'专业服务',
    children:[
      {
        value:'咨询',
        label:'咨询'
      },
      {
        value:'法律',
        label:'法律'
      },
      {
        value:'翻译',
        label:'翻译'
      },
      {
        value:'人力资源服务',
        label:'人力资源服务'
      },
      {
        value:'财务/审计/税务',
        label:'财务/审计/税务'
      },
      {
        value:'检测/认证',
        label:'检测/认证'
      },
      {
        value:'专利/商标/知识产权',
        label:'专利/商标/知识产权'
      },
      {
        value:'其他专业服务',
        label:'其他专业服务'
      }
    ]
  },
  {
    value:'房地产/建筑',
    label:'房地产/建筑',
    children:[
      {
        value:'房地产开发',
        label:'房地产开发'
      },
      {
        value:'工程施工',
        label:'工程施工'
      },
      {
        value:'建筑设计',
        label:'建筑设计'
      },
      {
        value:'装修装饰',
        label:'装修装饰'
      },
      {
        value:'建材',
        label:'建材'
      },
      {
        value:'地产经纪/中介',
        label:'地产经纪/中介'
      },
      {
        value:'物业服务',
        label:'物业服务'
      }
    ]
  },
  {
    value:'汽车',
    label:'汽车',
    children:[
      {
        value:'汽车生产',
        label:'汽车生产'
      },
      {
        value:'汽车零部件',
        label:'汽车零部件'
      },
      {
        value:'4S店/后市场',
        label:'4S店/后市场'
      }
    ]
  },
  {
    value:'机械/制造',
    label:'机械/制造',
    children:[
      {
        value:'机械设备/机电/重工',
        label:'机械设备/机电/重工'
      },
      {
        value:'仪器仪表/工业自动化',
        label:'仪器仪表/工业自动化'
      },
      {
        value:'原材料及加工/模具',
        label:'原材料及加工/模具'
      },
      {
        value:'印刷/包装/造纸',
        label:'印刷/包装/造纸'
      },
      {
        value:'船舶/航天/航空',
        label:'船舶/航天/航空'
      }
    ]
  },
  {
    value:'消费品',
    label:'消费品',
    children:[
      {
        value:'食品/饮料/烟酒',
        label:'食品/饮料/烟酒'
      },
      {
        value:'日化',
        label:'日化'
      },
      {
        value:'服装/纺织/皮革',
        label:'服装/纺织/皮革'
      },
      {
        value:'家具/家电/家居',
        label:'家具/家电/家居'
      },
      {
        value:'玩具/礼品',
        label:'玩具/礼品'
      },
      {
        value:'珠宝/首饰',
        label:'珠宝/首饰'
      },
      {
        value:'工艺品/收藏品',
        label:'工艺品/收藏品'
      },
      {
        value:'办公用品及设备',
        label:'办公用品及设备'
      }
    ]
  },
  {
    value:'服务业',
    label:'服务业',
    children:[
      {
        value:'餐饮',
        label:'餐饮'
      },
      {
        value:'酒店',
        label:'酒店'
      },
      {
        value:'旅游',
        label:'旅游'
      },
      {
        value:'美容/美发',
        label:'美容/美发'
      },
      {
        value:'婚庆/摄影',
        label:'婚庆/摄影'
      },
      {
        value:'其他服务业',
        label:'其他服务业'
      }
    ]
  },
  {
    value:'能源/化工/环保',
    label:'能源/化工/环保',
    children:[
      {
        value:'石油/石化',
        label:'石油/石化'
      },
      {
        value:'化工',
        label:'化工'
      },
      {
        value:'矿产/地质',
        label:'矿产/地质'
      },
      {
        value:'采掘/冶炼',
        label:'采掘/冶炼'
      },
      {
        value:'电力/热力/燃气/水利',
        label:'电力/热力/燃气/水利'
      },
      {
        value:'新能源',
        label:'新能源'
      },
      {
        value:'环保',
        label:'环保'
      }
    ]
  },
  {
    value:'政府/非盈利机构/其他',
    label:'政府/非盈利机构/其他',
    children:[
      {
        value:'政府/公共事业',
        label:'政府/公共事业'
      },
      {
        value:'非盈利机构',
        label:'非盈利机构'
      },
      {
        value:'农/林/牧/渔',
        label:'农/林/牧/渔'
      },
      {
        value:'其他行业',
        label:'其他行业'
      }
    ]
  }
]
export default company_pro_options