const job_name_options=[
  {
    value:'高级管理',
    label:'高级管理',
    children:[
      {
        value:'高级管理职位',
        label:'高级管理职位'
      }
    ]
  },
  {
    value:'技术',
    label:'技术',
    children:[
      {
        value:'后端开发',
        label:'后端开发'
      },
      {
        value:'移动开发',
        label:'移动开发'
      },
      {
        value:'测试',
        label:'测试'
      },
      {
        value:'运维/技术支持',
        label:'运维/技术支持'
      },
      {
        value:'数据',
        label:'数据'
      },
      {
        value:'项目管理',
        label:'项目管理'
      },
      {
        value:'硬件开发',
        label:'硬件开发'
      },
      {
        value:'前端开发',
        label:'前端开发'
      },
      {
        value:'通信',
        label:'通信'
      },
      {
        value:'电子/半导体',
        label:'电子/半导体'
      },
      {
        value:'高端技术职位',
        label:'高端技术职位'
      },
      {
        value:'人工智能',
        label:'人工智能'
      },
      {
        value:'销售技术支持',
        label:'销售技术支持'
      },
      {
        value:'其他技术职位',
        label:'其他技术职位'
      }
    ]
  },
  {
    value:'产品',
    label:'产品',
    children:[
      {
        value:'产品经理',
        label:'产品经理'
      },
      {
        value:'高端产品职位',
        label:'高端产品职位'
      },
      {
        value:'其他产品职位',
        label:'其他产品职位'
      }
    ]
  },
  {
    value:'设计',
    label:'设计',
    children:[
      {
        value:'视觉/交互设计',
        label:'视觉/交互设计'
      },
      {
        value:'游戏设计',
        label:'游戏设计'
      },
      {
        value:'用户研究',
        label:'用户研究'
      },
      {
        value:'高端设计职位',
        label:'高端设计职位'
      },
      {
        value:'非视觉设计',
        label:'非视觉设计'
      },
      {
        value:'其他设计职位',
        label:'其他设计职位'
      }
    ]
  },
  {
    value:'运营',
    label:'运营',
    children:[
      {
        value:'运营',
        label:'运营'
      },
      {
        value:'编辑',
        label:'编辑'
      },
      {
        value:'客服',
        label:'客服'
      },
      {
        value:'高端运营职位',
        label:'高端运营职位'
      },
      {
        value:'其他运营职位',
        label:'其他运营职位'
      }
    ]
  },
  {
    value:'市场',
    label:'市场',
    children:[
      {
        value:'政府事务',
        label:'政府事务'
      },
      {
        value:'市场/营销',
        label:'市场/营销'
      },
      {
        value:'公关媒介',
        label:'公关媒介'
      },
      {
        value:'会务会展',
        label:'会务会展'
      },
      {
        value:'广告',
        label:'广告'
      },
      {
        value:'高端市场职位',
        label:'高端市场职位'
      },
      {
        value:'其他市场职位',
        label:'其他市场职位'
      }
    ]
  },
  {
    value:'人事/财务/行政',
    label:'人事/财务/行政',
    children:[
      {
        value:'人力资源',
        label:'人力资源'
      },
      {
        value:'行政',
        label:'行政'
      },
      {
        value:'财务',
        label:'财务'
      },
      {
        value:'法务',
        label:'法务'
      },
      {
        value:'其他职能职务',
        label:'其他职能职务'
      }
    ]
  },
  {
    value:'金融',
    label:'金融',
    children:[
      {
        value:'投融资',
        label:'投融资'
      },
      {
        value:'风控',
        label:'风控'
      },
      {
        value:'税务审计',
        label:'税务审计'
      },
      {
        value:'银行',
        label:'银行'
      },
      {
        value:'互联网金融',
        label:'互联网金融'
      },
      {
        value:'保险',
        label:'保险'
      },
      {
        value:'证券',
        label:'证券'
      },
      {
        value:'其他金融职位',
        label:'其他金融职位'
      }
    ]
  },
  {
    value:'医疗健康',
    label:'医疗健康',
    children:[
      {
        value:'临床试验',
        label:'临床试验'
      },
      {
        value:'医生/医技',
        label:'医生/医技'
      },
      {
        value:'护士/护理',
        label:'护士/护理'
      },
      {
        value:'健康整形',
        label:'健康整形'
      },
      {
        value:'生物制药',
        label:'生物制药'
      },
      {
        value:'医疗器械',
        label:'医疗器械'
      },
      {
        value:'药店',
        label:'药店'
      },
      {
        value:'其他医疗健康职位',
        label:'其他医疗健康职位'
      }
    ]
  },
  {
    value:'服务业',
    label:'服务业',
    children:[
      {
        value:'餐饮',
        label:'餐饮'
      },
      {
        value:'酒店',
        label:'酒店'
      },
      {
        value:'零售',
        label:'零售'
      },
      {
        value:'美容保健',
        label:'美容保健'
      },
      {
        value:'运动健身',
        label:'运动健身'
      },
      {
        value:'婚礼/花艺',
        label:'婚礼/花艺'
      },
      {
        value:'宠物服务',
        label:'宠物服务'
      },
      {
        value:'安保/家政/维修',
        label:'安保/家政/维修'
      },
      {
        value:'其他服务业职位',
        label:'其他服务业职位'
      }
    ]
  },
  {
    value:'其他',
    label:'其他',
    children:[
      {
        value:'其他职位类别',
        label:'其他职位类别'
      }
    ]
  },
]
export default job_name_options
